### ISSUE TITLE
Elastic Beanstalk stack creation failed

### ISSUE THREAD

**Issue by gautam-nutalapati** [awslabs/eb-java-scorekeep#16]
Hi, 

On branch `xray-gettingstarted` using `2-deploy.sh` fails to create stack properly. My user has admin access.
Below are few things I did to make it work. Please see if we can fix this or if I am doing something wrong. 
Hopefully this is helpful for anyone else facing same issues. I am not sure if these are ideal fixes but I was able to being up the stack.

1. Minor: stack complains its using unsupported platform version. I changed `arn:aws:elasticbeanstalk:::platform/Java 8 running on 64bit Amazon Linux` to `arn:aws:elasticbeanstalk:::platform/Corretto 8 running on 64bit Amazon Linux 2/3.2.5`.
2. stack creation failed due to error `Attribute: EndpointURL was not found for resource: BETA. Rollback requested by user.` Underlying errors that caused this:
2.2. `AWSEBLoadBalancer` failed to create with reason `Issue found with the default subnets: VPC vpc-189b1e73 has no internet gateway (Service: AmazonElasticLoadBalancing; Status Code: 409; Error Code: InvalidConfigurationRequest; Request ID: 7b5d4f96-8148-40d5-ba7f-896dc2c74d5c; Proxy: null)`
Solution: I created InternetGateway and assigned to VPC manually
2.3. Elastic BeanStalk environment stack fails with error `WaitCondition timed out. Received 0 conditions when expecting 1`. My guess is, EC2 instance that gets spun up doesn't make HTTPS call to satisfy wait condition.
*Solution*: Not sure if this is a definite fix, but I spun up a EC2 instance with my key pair within same VPC, Security group and added NAT gateway route to routing table and logged in to instance, and executed that https request.
3. Minor: `template.yml` has email parameter, if it's mandatory for updating that email, `2-deploy.sh` script should probably ask for this variable and pass it on.

**Comment by mwunderl** [comment]
Hi Gautam, thanks for your feedback
1 - Platform is updated to Corretto 8 in https://github.com/aws-samples/eb-java-scorekeep/pull/18
2 - `vpc-189b1e73 has no internet gateway` indicates that your default VPC's internet gateway has been deleted. This is not common but it will prevent you from creating Elastic Beanstalk environments in your default VPC.  Try using the VPC console to [recreate your default VPC](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html#create-default-vpc)
3 - This is intentional, to show an error in the service map and how to find the exception. See the readme or [tutorial](https://docs.aws.amazon.com/xray/latest/devguide/xray-gettingstarted.html#xray-gettingstarted-console) for instructions.

**Comment by mwunderl** [comment]
The v2 release for the `xray-gettingstarted` branch is published: https://github.com/aws-samples/eb-java-scorekeep/releases/tag/xray-gs-v2
